LuceleLanches/pedidoslanches/src/main/java/br/com/lucelelanches/model/entity/Pedido.java
package br.com.lucelelanches.model.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

/**
 * Entidade que representa o pedido finalizado.
 * @author thiago.franzini
 *
 */
public class Pedido implements Serializable {

	private static final long serialVersionUID = -2360956230268481135L;
	private Integer id;
	private String nomeUsuario;
	private String endereco;
	private List<Lanche> lanchesPedido;
	private BigDecimal valorPedido;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNomeUsuario() {
		return nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public List<Lanche> getLanchesPedido() {
		return lanchesPedido;
	}

	public void setLanchesPedido(List<Lanche> lanchesPedido) {
		this.lanchesPedido = lanchesPedido;
	}

	public BigDecimal getValorPedido() {
		return valorPedido;
	}

	public void setValorPedido(BigDecimal valorPedido) {
		this.valorPedido = valorPedido;
	}

}

LuceleLanches/pedidoslanches/src/main/java/br/com/lucelelanches/controller/PedidosController.java
package br.com.lucelelanches.controller;

import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import br.com.lucelelanches.model.bo.ingredientes.IngredientesBO;
import br.com.lucelelanches.model.bo.lanches.LanchesBO;
import br.com.lucelelanches.model.entity.Lanche;
import br.com.lucelelanches.model.entity.Pao;
import br.com.lucelelanches.model.entity.Pedido;
import br.com.lucelelanches.model.entity.Queijo;
import br.com.lucelelanches.model.entity.Recheio;
import br.com.lucelelanches.model.entity.enums.Molhos;
import br.com.lucelelanches.model.entity.enums.Salada;
import br.com.lucelelanches.model.entity.enums.Temperos;

/**
 * Controller utilizado para o controle dos componentes apresentados em tela.
 * @author thiago
 *
 */
@Component
@Scope("session")
public class PedidosController  {

	private Pedido pedido;
	private Lanche lancheSelecionado;
	private Lanche lanche;
	private List<Lanche> listaLanches;
	private List<Pao> tiposDePaes;
	private List<Queijo> listaQueijos;
	private List<Recheio> listaRecheios;
	private Temperos[] temperosSelecionados;
	private Molhos[] molhosSelecionados;

	@Autowired
	private LanchesBO lanchesBO;
	@Autowired
	private IngredientesBO ingredientesBO;
	
	@PostConstruct
	private void init() {
		this.listaLanches = lanchesBO.listarLanches();
		this.tiposDePaes = ingredientesBO.listarPaes();
		this.listaQueijos = ingredientesBO.listarQueijos();
		this.listaRecheios = ingredientesBO.listarRecheios();
		this.pedido = new Pedido();
		this.lancheSelecionado = new Lanche();
		this.lanche = new Lanche();
	}

	
	
	
	public void salvarLanche(){
		
	}
	
	// **** Getters and Setters *****
	
	public List<Lanche> getListaLanches() {
		return listaLanches;
	}

	public void setListaLanches(List<Lanche> listaLanches) {
		this.listaLanches = listaLanches;
	}

	public List<Queijo> getListaQueijos() {
		return listaQueijos;
	}

	public void setListaQueijos(List<Queijo> listaQueijos) {
		this.listaQueijos = listaQueijos;
	}

	public List<Pao> getTiposDePaes() {
		return tiposDePaes;
	}

	public void setTiposDePaes(List<Pao> tiposDePaes) {
		this.tiposDePaes = tiposDePaes;
	}

	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public List<Recheio> getListaRecheios() {
		return listaRecheios;
	}

	public void setListaRecheios(List<Recheio> listaRecheios) {
		this.listaRecheios = listaRecheios;
	}
	
	public List<Salada> getListaSalada(){
		return Salada.listarSaladas();
	}
	
	public List<Molhos> getListaMolhos(){
		return Molhos.listarMolhos();
	}
	
	public List<Temperos> getListaTemperos(){
		return Arrays.asList(Temperos.values());
	}


	public Molhos[] getMolhosSelecionados() {
		return molhosSelecionados;
	}

	public void setMolhosSelecionados(Molhos[] molhosSelecionados) {
		this.molhosSelecionados = molhosSelecionados;
	}
	
	public void setTemperosSelecionados(Temperos[] temperos){
		this.temperosSelecionados = temperos;
	}
	
	public Temperos[] getTemperosSelecionados(){
		return temperosSelecionados;
	}


	public Lanche getLancheSelecionado() {
		return lancheSelecionado;
	}


	public void setLancheSelecionado(Lanche lancheSelecionado) {
		this.lancheSelecionado = lancheSelecionado;
	}


	public Lanche getLanche() {
		return lanche;
	}


	public void setLanche(Lanche lanche) {
		this.lanche = lanche;
	}
}

LuceleLanches/pedidoslanches/src/main/webapp/pedidos/pedidos.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>LuceneLanches</title>
</h:head>

    <h:body>
    	
    	
    	<h:form id="formPedido">
    	
		    <h:commandLink value="#{msgs.portuguese}" action="#{localeController.portugueseLocale}" /> |
		    <h:commandLink value="#{msgs.english}" action="#{localeController.englishLocale}" />
		    
		    <br></br>
		    <br></br>
		    <br></br>
		    <br></br>
		    
		    <table>
		    	<tr>
			    	<td colspan="2">
						<p:inputText id="nomePedido" label="nomePedido" size="40"  />
						<p:watermark for="nomePedido" value="#{msgs.name}"/>		    	    		
			    	</td>
		    		<td></td>
		    		<td></td>
		    	</tr>
		    	
		    	<tr>
			    	<td colspan="2">
						<p:inputText id="endereco"  label="endereco" size="40"   />
						<p:watermark for="endereco" value="#{msgs.address}"/>		    	    		
			    	</td>
		    		<td></td>
		    		<td></td>
		    	</tr>
		    
		    </table>
		    
		<p:panel id="panelLaches">		    
		    <table>
		    	<tr>
		    		<td colspan="2">
			    		<p:selectOneMenu>
							<f:selectItem itemLabel="#{msgs.listOfSnacks}" noSelectionOption="true"/>		    		
			    		</p:selectOneMenu>
		    		</td>
		    		<td></td>
		    		<td></td>
		    	</tr>
		    	
		    	<tr>
		    		<td>
		    			<h:outputLabel value="${msgs.typeOfBread}" />
		    		</td>
		    		<td>
			    		<p:selectOneMenu value="#{pedidosController.lanche.pao}" >
							<f:selectItem itemLabel="#{msgs.select}" noSelectionOption="true"/>	
							<f:selectItems value="#{pedidosController.tiposDePaes}" var="pao" itemLabel="#{pao.nomePao}" itemValue="#{pao.id}"/>	    		
			    		</p:selectOneMenu>
			    	</td>	
			    	<td></td>
		    	</tr>
		    	
		    	<tr>
		    		<td>
						<h:outputLabel value="${msgs.cheese}" />		    		
		    		</td>
		    		<td>
			    		<p:selectOneMenu value="#{pedidosController.lanche.queijo}">
							<f:selectItem itemLabel="#{msgs.select}" noSelectionOption="true"/>
							<f:selectItems value="#{pedidosController.listaQueijos}" var="queijo" itemLabel="#{queijo.nomeQueijo}" itemValue="#{queijo.id}"/>			    		
			    		</p:selectOneMenu>
			    	</td>	
			    	<td></td>
		    	</tr>
		    	
		    	<tr>
		    		<td>
						<h:outputLabel value="${msgs.filling}" />		    		
		    		</td>
		    		<td>
			    		<p:selectOneMenu value="#{pedidosController.lanche.recheio}">
			    			<f:selectItem itemLabel="#{msgs.select}" noSelectionOption="true"/>
			    			<f:selectItems value="#{pedidosController.listaRecheios}" var="recheio" itemLabel="#{recheio.tipoRecheio}" itemValue="#{recheio.id}"/>
			    		</p:selectOneMenu>
			    	</td>	
			    	<td></td>
		    	</tr>
		    	
		    	<tr>
		    		<td>
						<h:outputLabel value="#{msgs.salad}" />		    		
		    		</td>
		    		<td>
			    		<p:selectOneRadio value="#{pedidosController.lanche.salada}">
							<f:selectItems  value="#{pedidosController.listaSalada}" var="salada"  itemValue="#{salada}" itemLabel="#{msgs[salada.label]}"/>
			    		</p:selectOneRadio>
			    	</td>
			    	<td></td>	
		    	</tr>
		    	<tr>
		    		<td>
						<h:outputLabel value="${msgs.sauces}" />		    		
		    		</td>
		    		<td>
			    		<p:selectManyCheckbox value="#{pedidosController.lanche.listaMolhos}">
			    			<f:selectItems value="#{pedidosController.listaMolhos}" var="molhos" itemLabel="#{msgs[molhos.label]}" itemValue="#{molhos}"/>
			    		</p:selectManyCheckbox>
			    	</td>	
			    	<td></td>
		    	</tr>
		    	
		    	<tr>
		    		<td>
		    			<h:outputLabel value="${msgs.spices}" />
		    		</td>
		    		<td>
			    		<p:selectManyCheckbox value="#{pedidosController.temperosSelecionados}">
			    			<f:selectItems value="#{pedidosController.listaTemperos}" var="tempero" itemLabel="#{msgs[tempero.label]}" itemValue="#{tempero}" />
			    		</p:selectManyCheckbox>
			    	</td>	
			    	<td></td>
		    	</tr>
		    </table>
		   </p:panel> 
		   
		    <p:remoteCommand name="remote" action="#{pedidosController.testeValor}"/>
		    
		    <p:panel>
			    <p:selectOneListbox value="#{pedidosController.lancheSelecionado}" style="width: 200px;"  id="lanchesPadrao" converter="conversorLanche">
					<p:ajax immediate="true" event="change" listener="#{pedidosController.testeValor}"/>			    	
					<f:selectItems value="#{pedidosController.listaLanches}" var="lanche" itemLabel="#{lanche.nomeLanche}" itemValue="#{lanche}">
						<f:attribute name="lancheEscolhido" value="#{lanche}" />  
                        <f:param name="lanchePadraoEscolhido" value="#{lanche}" />  
					</f:selectItems>
				</p:selectOneListbox>
			</p:panel>
		    
		    
		    <h:commandButton action="#{pedidosController.salvarLanche}" value="Salvar" /> 
		    
		    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
    	</h:form>
    	
	</h:body>
</html>